# Premium-minds - pm-persistence-utils .travis.yml

language: java

jdk:
    - oraclejdk8

after_success:
    - "./share/deploy/deploy-snapshot.sh"

notifications:
    email:
        recipients:
            - andre.camilo@premium-minds.com
        on_failure: always
